// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0jHOCns8E2w-IxGawxVgWk2IO6ZSJfo',
    appId: '1:195565641933:android:276536ff2c9980a436c984',
    messagingSenderId: '195565641933',
    projectId: 'dot-thenoteapp-1122',
    storageBucket: 'dot-thenoteapp-1122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmy-0-YC7EWqB_6VG6UvlPi87ZUASPFcE',
    appId: '1:195565641933:ios:f9a287280d93468b36c984',
    messagingSenderId: '195565641933',
    projectId: 'dot-thenoteapp-1122',
    storageBucket: 'dot-thenoteapp-1122.appspot.com',
    iosBundleId: 'com.dot.dot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmy-0-YC7EWqB_6VG6UvlPi87ZUASPFcE',
    appId: '1:195565641933:ios:524a866efa884cbf36c984',
    messagingSenderId: '195565641933',
    projectId: 'dot-thenoteapp-1122',
    storageBucket: 'dot-thenoteapp-1122.appspot.com',
    iosBundleId: 'com.dot.dot.RunnerTests',
  );
}
